"""add packing column to products

Revision ID: cce7ec617feb
Revises: b669cc275820
Create Date: 2026-09-13 14:45:57.509540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cce7ec617feb'
down_revision = 'b669cc275820'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('village', sa.String(length=200), nullable=True))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('packing', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('hsn_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('gst_percent', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('manufacturing_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('manufacturing_date')
        batch_op.drop_column('gst_percent')
        batch_op.drop_column('hsn_code')
        batch_op.drop_column('packing')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('village')

    # ### end Alembic commands ###
